Caption support
globekeeper/matrix-ios-sdk pull request #1
Opened 2021-04-26 09:31 UTC by artemkrachulov

Attached optional caption property in the event info dictionary: `sendImage` and `sendVideo` methods

2021-04-26 09:38 UTC, ferologics requested changes
Can you add nullability to obj-c `caption` function parameters and simplify the logic for setting caption on `msgContent` dictionary?

2021-04-26 09:38 UTC, ferologics commented on MatrixSDK/Data/MXRoom.m
> +    }
why not just?
```suggestion
    if caption {
        msgContent[@"caption"] = msgContent
    }
```

2021-04-26 09:38 UTC, ferologics commented on MatrixSDK/Data/MXRoom.m
> +                      caption:(NSString*)caption
maybe use `nullable`?

2021-04-26 09:50 UTC, artemkrachulov commented on MatrixSDK/Data/MXRoom.m
> +    }
optimised

2021-04-26 09:52 UTC, danpe commented
Guys, in general, why is this a fork from xinsight/matrix-ios-sdk and not matrix-org/matrix-ios-sdk ?

2021-04-26 09:54 UTC, artemkrachulov commented on MatrixSDK/Data/MXRoom.m
> +                      caption:(NSString*)caption
will work fine without `nullable` keyword, same as previous methods.

2021-04-26 09:54 UTC, ferologics commented
@danpe because of the missing Carthage support for MatrixSDK.

2021-04-26 09:57 UTC, ferologics approved these changes

2021-04-28 07:31 UTC, merged

2021-04-28 07:32 UTC, ferologics commented
@danpe the fork base has been updated to matrix-org/matrix-ios-sdk :)